README.md
Was just browsing through, not meant in a controversial way but it seems more useful to have a more clear differences section from other css-in-js systems.
At least, these areas confused me a little, so I tried to make it simpler to see the contrast.
Keep in mind: stuff removed I think is handled by Aphrodite and others, so less a comparison than just a note about glamour. I may be wrong here!
=> More accurate css-in-js comparison

examples/index.js
This PR fixes the app module path reference for hot-reloading.
=> Fixed module path for HMR

src/index.js
fixes bug in previous #41 fix, sorry.
=> Fix bug. Hash was not considered in falsy values cleanup.

src/utils.js
Just a simple update to the reference.
=> Fix utils import

docs/createElement.md
I think that documentation is outdated. Updated according to what worked for me.
=> Update react doc

docs/composition.md, src/clean.js, src/index.js, tests/index.js
This PR is a natural extension of #41 with fixes for most of #51 problems. I'm sending it in one shot as they are related.
Included:
1. Proper tests for falsy values handling.
2. Falsy values filtering for all functions in the main module. 
3. Style() and friends return {} if there is nothing to add to stylesheet.
Todo:
1. clean clean.js, check performance
2. more tests
3. more docs?
=> [WIP] ignore empty and falsy values

examples/perf.js, package.json, src/CSSPropertyOperations.js, src/index.js, tests/index.js, tests/karma.conf.js
`toString()` to the rescueeeeeee
basically, the 'rule' object converts to a classname when treated as a string, and we add that classname to the same css we add for data attributes. BOOM.
=> experimental support for classnames(!!!)

src/index.js, tests/index.js
* throwing error for cache miss
=> Multiple versions of glamor #79

package.json
Append repository and homepage field for `npm repo glamor`
=> Fill repository and homepage field

docs/composition.md
=> docs: add link to `share!`

docs/howto.md
Following up from https://github.com/threepointone/glamor/issues/124
=> Add docs for combined selectors

src/sheet.js, tests/index.js
fixes #142 
Note: this is a naive first attempt to fix this issue, because its breaks our production SPAs ATM :)
=> pulls @import rules to the top of the stylesheet

.gitignore, src/reset.js
Normalize.css bumped up to version 5.0
=> upgraded glamor/reset

docs/weakmaps.md
Really enjoyed this blog post! Cleaned up a few things while reading through it. This cleans up some of the grammar and consistency for this post.
* Consistent semicolons.
* Consistent periods at ending of lists.
* Consistent spacing in conditional statements.
* Spaces in example code to simplify grokking.
=> Grammatical consistency for weakmaps.md

index.d.ts
updated allowed values for css() params to match the clean() function
=> enhanced typings

src/index.js
This fix this issue: https://github.com/threepointone/glamor/issues/14#issuecomment-270473786
=> Fix placeholder support

index.d.ts
@donaldpipowitch plz have a look :)
=> fix for #190

src/reset.js
As mentioned in the docs, only a single rule can be inserted at a time in production mode. The reset was inserting multiple and some were getting lost.
=> ensure reset works in production

.travis.yml, package.json
This PR adds a script which runs CI tests only for updated packages (via lerna updated) to speedup them :)
=> Only run tests for updated packages

docs/migration.md, src/index.js
Deprecation warnings and migration docs added to v2. Needed for https://github.com/threepointone/glamor/issues/213.
=> added deprecation warnings

docs/npm-modules.md
=> Docs for NPM builds and browserification

README.md
[`jest-glamor-react`](https://github.com/kentcdodds/jest-glamor-react)
=> docs(extras): add link to `jest-glamor-react`

docs/howto.md
=> css selector prettify/typo fix

docs/howto.md
=> Tidy up animations docs

packages/glamor-jsxstyle/src/index.js
Added an Inline component for closer parity to jsxstyle
=> Adding Inline jsxstyle component

src/plugins.js
Fixes https://github.com/threepointone/glamor/issues/310
=> Avoid stringifying content entries attr() calc() counter() counters()
