threepointone/glamor

- src/autoprefix.js
- tests/index-test.js
Gettin' a lil' over-zealous w the semi-colon removal, my friend... ;)
> Fix display:flex

- CONTRIBUTING.md
The `demo` folder was moved over to `examples` recently.
> Renamed "demo" to "examples" in contrib doc

- README.md
The current link goes out to a 404 on github.
> Fixes the 'getskeleton' link

- src/react.js
Fix for #65 
Allows a themed component to be used in a part of the component tree where the theme has not been applied.
> Use the spread operator defensively

- examples/index.js
Looks like the import path was changed from `tweet` to `classes` here 92ffdb43eedc017575d045162caa94d1d4471b99 which breaks the example app. Is this the right way to do? Or change the folder name to `classes`?
> import app from right path

- docs/howto.md
As a newbie it wasn't clear to me where methods like `$` and to a lesser extent `merge` and `style` were coming form. This might help, or you might think it clutters up the examples.
> Added import statements to examples

- docs/composition.md
- react.d.ts
- src/react.js
- tests/index.js
Like discussed in glamor gitter chatroom this PR adds a better way for composing react components with glamor styles.
``` typescript
const cardButton = style({
height: '20px',
color: 'green'
});
const defaultButtonStyle = style({
color: 'red',
height: '50px',
border: '1px solid black'
});
let Button: SFC<HTMLProps<HTMLButtonElement>> = (props) => 
<button {...propMerge(defaultButtonStyle, props)}/>;
let CardButton: SFC<HTMLProps<HTMLButtonElement>> = (props) => 
<Button {...propMerge(cardButton, props)}/>;
let AnotherButton: SFC<HTMLProps<HTMLButtonElement>> = (props) => 
<button {...defaultButtonStyle} {...props}/>;
let AnotherCardButton: SFC<HTMLProps<HTMLButtonElement>> = (props) => 
<AnotherButton {...cardButton} {...props}/>;
```
Will result in
> added propMerge() in react package

- index.d.ts
Hi, I think glamor is so great thing!
I often want to use `insertGlobal()` when append the global style rules(e.g. `html { font-size: 16px }`).
But it is not exist in typings (I usually using with TypeScript).
Please merge this PR.
> Add a typing for `insertGlobal ()`

- src/CSSPropertyOperations/index.js
- tests/index.js
CSS custom properties, also called CSS variables, are property names
prefixed with `--`. In that case, don't process the property name, nor
the value, and add them as they are.
Now the property name is converted from camel case to kebab case and `px` is appended to the value if it is a number. E.g.:
```
style({'--myVar': 50})
```
is converted to `--my-var:50px;`, when it should be `--myVar:50;`
I created this jsbin where you can test it:
https://jsbin.com/mijixu/6/edit?html,output
> Add support for CSS custom properties

- src/index.js
I wonder why this error isn't thrown in all cases, but only certain times. It looks like `fontFace` is exported as `undefined` every time. You basically did this:
```
function css() {}
const fontFace = css.fontFace
css.fontFace = () => {}
console.log(fontFace === undefined) // true 
```
I changed the order so we have this:
```
function css() {}
css.fontFace = () => {}
const fontFace = css.fontFace
console.log(fontFace === undefined) // false 
```
> fixed #149

- src/sheet.js
Small bugfix - `sheet` is undefined. Bug was introduced by #151
> Fix server side rendering

- tests/index.js
Adds a test that fails in Chrome and succeeds in Phantom when
combining shorthand and longhand properties. The bug seems to be
ordering-related as the shorthand `font` appears at the bottom of the
declared styles even though it is declared in the first glamor style
object.
> Add failing test for shorthand/longhand merge

- docs/createElement.md
There was an extra half of a closing div tag
> Fixed typo in documentation

- docs/css.md
I guess it shouldn't be `:hover:` as it's `:hover` in the next example.
> Fixed typo in CSS demo

- docs/migration.md
A change to the migration doc because the `glamor-react` [re-exports all of glamor](https://github.com/threepointone/glamor/blob/1ce8d77afc489a012a2b0bdc851de050ec8535da/packages/glamor-react/src/index.js#L5), thus making an explicit dependency on `glamor` in a user's app's package.json unnecessary.
> remove unnecessary glamor dependency in v3 migration

- packages/glamor-jsxstyle/tests/index.js
- packages/glamor/src/index.js
- packages/glamor/tests/index.js
They should exist in "css framework" or utils type packages instead.
Addresses @donaldpipowitch's comment here: https://github.com/threepointone/glamor/issues/83#issuecomment-281660522
> Remove media-query presets from core

- docs/howto.md
There are extra quotation mark and parenthesis, which breaks media queries example. Fixed :thumbsup:
> Fixed typo in "howto" doc

- docs/server.md
Suppose we have:
`css = '.css-abc:before { content: "" }'`
then:
`<style>{css}</style>`
gives:
`<style>.css-abc:before { content: &quot;&quot; } </style>`
... which is not the desired outcome. Whereas:
`<style dangerouslySetInnerHTML={{ __html: css }} />`
will give:
`<style>.css-abc:before { content: "" } </style>`
Updating docs/server.md so others aren't misled.
> Using the docs suggested way to render on the server side, content: "" in ::before, ::after gets encoded as &quote;

- src/plugins.js
Because of this: rollup/rollup-plugin-commonjs#96 Glamor's es6 build isn't importable into a Rollup build. Just ran into this now.
This should fix things up, and also better follows the [unambiguous grammar proposal](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module). (Yes, I know they're going with .mjs, but this still fits with the right spirit of the spec)
> Remove CommonJS call

- src/server.js
This does the same thing as tkh44/emotion#218.
This adds the ids for `keyframes` and `fontFace` to the `ids` returned from `renderStaticOptimized` so they're not reinserted on the client.
> Include ids for keyframes and fontFace in ids from renderStaticOptimized

- server.d.ts
As it looks like the TypeScript rewrite has been called off for now, I would like to add a few missing typings to the existing code base, namely for server-side rendering 🙂
> Add typings for glamor/server

- index.d.ts
**css.keyframes and css.fontFace**
Typings for `keyframes` and `fontFace` had been typed before, I just reordered and created aliases for `css.keyframes` and `css.fontFace`
**plugins**
I did not found a way to reuse `PluginSet` type inside plugins namespace, so I had to redeclare they.
**speedy and flush**
`speedy(boolean)` and `flush()` are simple void functions which had not yet been declared
> Add typings for plugins, speedy, flush, css.keyframes, css.fontFace

- package.json
When updating, I noticed that the TypeScript definitions for `'glamor/server'` added in #314 aren't actually included in the NPM bundle :flushed:
> Fix: Add server.d.ts to NPM bundle

- docs/howto.md
> Added example to child-selectors of using Glamor-generated class names
